require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe MeteoritesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Meteorite. As you add validations to Meteorite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'Alice', mass: 2.2, year: 1992, meteorite_class: 'A', latitude: 5.43, longitude: 2.54}
  }

  let(:invalid_attributes) {
    {name: 5, mass: 2.2, years: 'hello', meteorite_class: '', longitude: 2.54}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeteoritesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before do
    user = FactoryBot.create(:user)
    allow(controller).to receive(:authenticate_user!).and_return(true)
    allow(controller).to receive(:current_user).and_return(user)
  end

  describe "GET #index" do
    it "returns a success response" do
      Meteorite.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      meteorite = Meteorite.create! valid_attributes
      get :show, params: {id: meteorite.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      meteorite = Meteorite.create! valid_attributes
      get :edit, params: {id: meteorite.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Meteorite" do
        expect {
          post :create, params: {meteorite: valid_attributes}, session: valid_session
        }.to change(Meteorite, :count).by(1)
      end

      it "redirects to the created meteorite" do
        post :create, params: {meteorite: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Meteorite.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {meteorite: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: 'Alice', mass: 2.2, year: 1992, meteorite_class: 'B', latitude: 5.43, longitude: 2.54}
      }

      it "updates the requested meteorite" do
        meteorite = Meteorite.create! valid_attributes
        put :update, params: {id: meteorite.to_param, meteorite: new_attributes}, session: valid_session
        meteorite.reload
        #skip("Add assertions for updated state")
      end

      it "redirects to the meteorite" do
        meteorite = Meteorite.create! valid_attributes
        put :update, params: {id: meteorite.to_param, meteorite: valid_attributes}, session: valid_session
        expect(response).to redirect_to(meteorite)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        meteorite = Meteorite.create! valid_attributes
        put :update, params: {id: meteorite.to_param, meteorite: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested meteorite" do
      meteorite = Meteorite.create! valid_attributes
      expect {
        delete :destroy, params: {id: meteorite.to_param}, session: valid_session
      }.to change(Meteorite, :count).by(-1)
    end

    it "redirects to the meteorites list" do
      meteorite = Meteorite.create! valid_attributes
      delete :destroy, params: {id: meteorite.to_param}, session: valid_session
      expect(response).to redirect_to(meteorites_url)
    end
  end

end
